apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-basic-1776166996122
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/quay_xjiang/test-image:github-ba8fe7d138dbca546128df9495dd43d55fe650fa
        name: container-image  
